language: node_js
node_js: '8'
services:
  - docker

before_install:
  - sudo pip install --upgrade s3cmd

install: skip
  
script:
  # Set environment
  - mkdir -p packages
  - export DESTDIR=`realpath packages`
  - export TAG=${TAG:-$TRAVIS_BRANCH}
  - echo "> building from TAG $TAG"

  - export DISTROS=`ls distros`; for i in $DISTROS; do echo "Building for distro $i..." && ./dist-utils/build-package.sh $i -d $DESTDIR -t $TAG; done

  # Upload artifacts
  - export AWS_ACCESS_KEY_ID="AKIAJWBFLU34IVITPLHA"
  - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET
  - export AWS_DEFAULT_REGION=eu-west-1
  - echo $TRAVIS_PULL_REQUEST
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export DEPLOY=true; else export DEPLOY=false; fi
  - echo "Deploy for build is $DEPLOY..."
  - if [ "$DEPLOY" = "true" ] then shopt -s nullglob; for package in $DESTDIR/*.{deb,pkg.tar.zst,rpm}; do echo Uploading package to http://stremio-artifacts.s3.amazonaws.com/shell-linux/$TAG/$package; s3cmd --acl-public --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_ACCESS_KEY --force --region=$AWS_DEFAULT_REGION --add-header=Cache-Control:max-age=7200 put "$package" s3://stremio-artifacts/shell-linux/$TAG/; done; fi

notifications:
  slack:
    rooms:
      - stremio:74vRvYUJbhcl3IrYCbOIvTo3#installer-ci
    template: |
      %{repository}@%{branch}: build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) by %{author} %{result} in %{duration}
      %{message} - %{commit_message}"
