#!/bin/bash

rm -f /usr/bin/stremio

xdg-desktop-menu uninstall --mode system /opt/stremio/smartcode-stremio.desktop

cd /opt/stremio/icons || exit 1
regex="([^_]+)_([0-9]+).png$"
for file in *.png
do
	if [[ $file  =~ $regex ]]
	then
		icon="${BASH_REMATCH[1]##*/}"
		size="${BASH_REMATCH[2]}"
		xdg-icon-resource uninstall --context apps --size "$size" "$icon"
	fi
done
